x-base: &base

  build: .

  volumes:
    - .:/usr/workspace

  working_dir: /usr/workspace

  environment:
    BASE_URL: ${BASE_URL:?BASE_URL is required}
    API_TOKEN: ${API_TOKEN:?API_TOKEN is required}


services:
  all:
    <<: *base
    command: [ "pytest", "-sv", "--alluredir=allure-results", "--clean-alluredir" ]

  smoke:
    <<: *base
    command: [ "pytest", "-sv", "-m", "smoke", "--alluredir=allure-results", "--clean-alluredir" ]

  regression:
    <<: *base
    command: [ "pytest", "-sv", "-m", "regression", "--alluredir=allure-results", "--clean-alluredir" ]

  negative:
    <<: *base
    command: [ "pytest", "-sv", "-m", "negative", "--alluredir=allure-results", "--clean-alluredir" ]